apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce
resources: [../../base]
images:
  - name: ghcr.io/example/ecommerce-backend
    newName: ecommerce-backend
    newTag: dev
  - name: ghcr.io/example/ecommerce-frontend
    newName: ecommerce-frontend
    newTag: dev
