apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_PASSWORD: ecommerce_dev
  DATABASE_URL: postgresql+psycopg://ecommerce:ecommerce_dev@postgres:5432/ecommerce
